# -*- coding: utf-8 -*-
"""regras_proj_desenv_infantil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBv5i6jkwoThw_kD0-hyoUI9PyYrBLAv

###Instação e Importação de Bibliotecas
"""

!pip install pytholog

import pytholog as pl
from collections import OrderedDict

"""### Casos de teste

#### Criança 01 - Caso Adequado
"""

crianca_01 = {
    'nome': "junior",
    'idade_meses': "4",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "não verificado",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 02 -  Caso Alerta"""

crianca_02 = {
    'nome': "paulo",
    'idade_meses': "6",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "não verificado",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "ausente", #ausente/alerta
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "presente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "presente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 03 - Caso Atraso"""

crianca_03 = {
    'nome': "maria",
    'idade_meses': "4",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "ausente", #marco indicador de atraso de desenvolvimento - faixa etaria anterior
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "ausente", #ausente na faixa etaria da criança
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "ausente", #ausente na faixa etaria da criança
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "nao verificado",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 04 - Caso Atraso"""

crianca_04 = {
    'nome': "julia",
    'idade_meses': "6",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "ausente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "ausente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "4",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 05 -  Caso Adequado"""

crianca_05 = {
    'nome': "pedro",
    'idade_meses': "3",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 06 - Caso 1 mês - Atraso

"""

crianca_06 = {
    'nome': "gabriel",
    'idade_meses': "1",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "ausente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 08 - Caso 1 mês - Adequado"""

crianca_08 = {
    'nome': "naiara",
    'idade_meses': "1",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 07 - Caso Alerta

"""

crianca_07 = {
    'nome': "enzo",
    'idade_meses': "6",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "ausente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "ausente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "presente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 09 - Caso Atraso"""

crianca_09 = {
    'nome': "joao",
    'idade_meses': "6",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "ausente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "ausente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "presente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "presente",
                'registro_idade_mes': "6",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "presente",
                'registro_idade_mes': "5",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 10 - Caso Alerta"""

crianca_10 = {
    'nome': "kleber",
    'idade_meses': "3",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "09",
                'avaliacao': "ausente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "ausente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "presente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "ausente",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes':"",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 11 - Caso Alerta"""

crianca_11 = {
    'nome': "melissa",
    'idade_meses': "2",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "ausente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "",
                'avaliacao': "",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes':"",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""#### Criança 12 - Caso Atraso"""

crianca_12 = {
    'nome': "joana",
    'idade_meses': "2",
    'marcos': [
        {
            'postura': {
                'id_marco': "01",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'observa_rosto': {
                'id_marco': "02",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'reage_ao_som': {
                'id_marco': "03",
                'avaliacao': "presente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'eleva_cabeca': {
                'id_marco': "04",
                'avaliacao': "ausente",
                'registro_idade_mes': "1",
                'limite_superior_faixa_etaria': "1",
                'limite_inferior_faixa_etaria': "0"
            }
        },
        {
            'sorrir_quando_estimulada': {
                'id_marco': "05",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'abre_as_maos': {
                'id_marco': "06",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'emite_sons': {
                'id_marco': "07",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'movimenta_membros': {
                'id_marco': "08",
                'avaliacao': "presente",
                'registro_idade_mes': "2",
                'limite_superior_faixa_etaria': "2",
                'limite_inferior_faixa_etaria': "2"
            }
        },
        {
            'responde_ativamente_contato_social': {
                'id_marco': "",
                'avaliacao': "",
                'registro_idade_mes': "3",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'segura_objetos': {
                'id_marco': "10",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'emite_sons_ri_alto': {
                'id_marco': "11",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'levanta_cabeça_antebraço_bruco': {
                'id_marco': "12",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "4",
                'limite_inferior_faixa_etaria': "3"
            }
        },
        {
            'busca_ativa_objetos': {
                'id_marco': "13",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'leva_objetos_boca': {
                'id_marco': "14",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'localiza_som': {
                'id_marco': "15",
                'avaliacao': "",
                'registro_idade_mes': "",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        },
        {
            'muda_posicao_rolar': {
                'id_marco': "16",
                'avaliacao': "",
                'registro_idade_mes':"",
                'limite_superior_faixa_etaria': "6",
                'limite_inferior_faixa_etaria': "5"
            }
        }
    ]
}

"""### Filtragem dos dados das crianças"""

#Adicionar as crianças em uma lista
lista_criancas = [crianca_01,crianca_02,crianca_03,crianca_04,crianca_05,crianca_06,crianca_07, crianca_08, crianca_09, crianca_10, crianca_11, crianca_12]
print(*lista_criancas, sep='\n')

def filtro_crianca_idade(crianca):# Filtragem por Idade das regras
  lista_crianca_filtrada = []

  # Obtendo a idade da criança
  idade_crianca_meses = int(crianca['idade_meses'])
  crianca_filtrada = crianca.copy()

  for marco in crianca_filtrada['marcos']:
      chave_marco = list(marco.keys())[0]
      idade_marco_meses = int(marco[chave_marco]['limite_superior_faixa_etaria'])

      # Verificando se o marco de desenvolvimento é relevante para a idade da criança
      if idade_marco_meses <= idade_crianca_meses:
        lista_crianca_filtrada.append(marco)

  crianca_filtrada['marcos'] = lista_crianca_filtrada
  return crianca_filtrada

#Passando as criança filtradas pela idade

crianca_01_filtrada_idade = filtro_crianca_idade(lista_criancas[0])
print(crianca_01_filtrada_idade)

crianca_02_filtrada_idade = filtro_crianca_idade(lista_criancas[1])
print(crianca_02_filtrada_idade)

crianca_03_filtrada_idade = filtro_crianca_idade(lista_criancas[2])
print(crianca_03_filtrada_idade)

crianca_04_filtrada_idade = filtro_crianca_idade(lista_criancas[3])
print(crianca_04_filtrada_idade)

crianca_05_filtrada_idade = filtro_crianca_idade(lista_criancas[4])
print(crianca_05_filtrada_idade)

crianca_06_filtrada_idade = filtro_crianca_idade(lista_criancas[5])
print(crianca_06_filtrada_idade)

crianca_07_filtrada_idade = filtro_crianca_idade(lista_criancas[6])
print(crianca_07_filtrada_idade)

crianca_08_filtrada_idade = filtro_crianca_idade(lista_criancas[7])
print(crianca_08_filtrada_idade)

crianca_09_filtrada_idade = filtro_crianca_idade(lista_criancas[8])
print(crianca_09_filtrada_idade)

crianca_10_filtrada_idade = filtro_crianca_idade(lista_criancas[9])
print(crianca_10_filtrada_idade)

crianca_11_filtrada_idade = filtro_crianca_idade(lista_criancas[10])
print(crianca_11_filtrada_idade)

crianca_12_filtrada_idade = filtro_crianca_idade(lista_criancas[11])
print(crianca_12_filtrada_idade)

def filtro_crianca_avaliacao(crianca):# Filtragem por Avaliação deixando somente as regras que são "presentes" ou "ausentes"

  lista_crianca_filtrada = []
  crianca_filtrada = crianca.copy()
  for marco in crianca_filtrada['marcos']:
      chave_marco = list(marco.keys())[0]
      avaliacao = marco[chave_marco]['avaliacao']
      if avaliacao == "presente" or avaliacao == "ausente":
          lista_crianca_filtrada.append(marco)

  crianca_filtrada['marcos'] = lista_crianca_filtrada
  return crianca_filtrada

#Passando as criança filtradas pela idade para o filtro de avaliaçao

crianca_01_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_01_filtrada_idade)
print(crianca_01_filtrada_idade_avaliacao)

crianca_02_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_02_filtrada_idade)
print(crianca_02_filtrada_idade_avaliacao)

crianca_03_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_03_filtrada_idade)
print(crianca_03_filtrada_idade_avaliacao)

crianca_04_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_04_filtrada_idade)
print(crianca_04_filtrada_idade_avaliacao)

crianca_05_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_05_filtrada_idade)
print(crianca_05_filtrada_idade_avaliacao)

crianca_06_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_06_filtrada_idade)
print(crianca_06_filtrada_idade_avaliacao)

crianca_07_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_07_filtrada_idade)
print(crianca_07_filtrada_idade_avaliacao)

crianca_08_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_08_filtrada_idade)
print(crianca_08_filtrada_idade_avaliacao)

crianca_09_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_09_filtrada_idade)
print(crianca_09_filtrada_idade_avaliacao)

crianca_10_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_10_filtrada_idade)
print(crianca_10_filtrada_idade_avaliacao)

crianca_11_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_11_filtrada_idade)
print(crianca_11_filtrada_idade_avaliacao)

crianca_12_filtrada_idade_avaliacao = filtro_crianca_avaliacao(crianca_12_filtrada_idade)
print(crianca_12_filtrada_idade_avaliacao)

"""###Selecionar criança para avaliação"""

#Selecionar criança para a classificação do desenvolvimento
crianca = crianca_12_filtrada_idade_avaliacao

"""###Atualização da base de conhecimento"""

#Gera fatos dos dados das crianças
def gera_fatos_criancas(lista_criancas):
  fatos_criancas = []
  for c in lista_criancas:
    fato = f"crianca({c['nome']}, {c['idade_meses']})"
    fatos_criancas.append(fato)
  return fatos_criancas

fatos_criancas = gera_fatos_criancas([crianca])
print(*fatos_criancas, sep='\n')

#Gera fatos dos marcos
def gera_fatos_marcos(crianca_filtrada_idade_avaliacao):
    fatos_marco_desenvolvimento = [] #lista para armazenar a string
    marcos_lista = []

    marcos_crianca = crianca_filtrada_idade_avaliacao['marcos']
    for mrc_crianca in marcos_crianca:
        fato_marco_crianca = list(mrc_crianca.keys())[0]
        marco = fato_marco_crianca.split(')')[0]
        fato_marco = f"{marco}({crianca_filtrada_idade_avaliacao['nome']}, {mrc_crianca[fato_marco_crianca]['avaliacao']}, {mrc_crianca[fato_marco_crianca]['registro_idade_mes']}, {mrc_crianca[fato_marco_crianca]['limite_superior_faixa_etaria']})"
        fatos_marco_desenvolvimento.append(fato_marco)
        marcos_lista.append(marco)

    '''print(*fatos_marco_desenvolvimento , sep='\n' )
    print("-----")
    print(*marcos_lista , sep='\n' )
    print("-----")'''

    return fatos_marco_desenvolvimento, marcos_lista

# Para usar a função, você pode fazer o seguinte:
fatos_marco_desenvolvimento, marcos_lista = gera_fatos_marcos(crianca)

#Gera Regras dos marcos
def gera_regras_marcos(marcos_lista):
  regras_marcos = []
  regras_marcos_lista = list(OrderedDict.fromkeys(marcos_lista)) #retira duplicadas

  for rgr in regras_marcos_lista:
    regra_txt = f"{rgr}_presente(C) :- {rgr}(C ,presente, Reg_idade_marco, Grupo_mes_limite),crianca(C, Idade), (Reg_idade_marco <= Grupo_mes_limite and Idade >= Reg_idade_marco)"
    #regra_txt = f"{rgr}_presente(Cod,C,Veracidade) :- {rgr}(Cod,C ,presente, Reg_idade_marco, Grupo_mes_limite),crianca(Cod, C, _), Veracidade is Reg_idade_marco <= Grupo_mes_limite"
    regras_marcos.append(regra_txt)
  return regras_marcos

regras_marcos =  gera_regras_marcos(marcos_lista)
print(*regras_marcos, sep='\n')

#Atualização da base de conhecimento / Fatos + Regras
base_conhecimento = pl.KnowledgeBase("desenvolvimento_infantil")
fatos_e_regras = fatos_criancas + fatos_marco_desenvolvimento + regras_marcos
base_conhecimento(fatos_e_regras)
print(base_conhecimento)
print(*fatos_e_regras, sep='\n')

"""### Aplicação de consultas sobre a base de conhecimento"""

def consulta_marcos_presentes_para_crianca(crianca_nome,marcos_lista):
  lista_retorno_consulta = []

  for m in marcos_lista:
    consulta = f"{m}_presente({crianca_nome})"
    #print(consulta)
    resultado_consulta = base_conhecimento.query(pl.Expr(consulta))
    #print(resultado_consulta)
    #postura_presente(Cod,C) :- postura(Cod,C,presente,Reg_idade_marco, Grupo_mes_limite), Reg_idade_marco=< Grupo_mes_limite, criança(Cod,C,Idade), Idade>=Reg_idade_marco
    lista_retorno_consulta.append(resultado_consulta[0])

  return lista_retorno_consulta

def dev_adequado_crianca(crianca_nome,marcos_lista):
  resultados_marcos_lista = consulta_marcos_presentes_para_crianca(crianca_nome, marcos_lista)
  #print(*resultados_marcos_lista, sep='\n')

  classificacao = False
  for r_mrc in resultados_marcos_lista:
    #print(r_mrc)
    if r_mrc == "No":
      classificacao = False
      break
    else:
      classificacao = True

  return classificacao

resultados_marcos_lista = consulta_marcos_presentes_para_crianca(crianca['nome'], marcos_lista)

print(resultados_marcos_lista)

marcos_ausentes = []
for i in range(len(resultados_marcos_lista)):
  #print(resultados_marcos_lista[i])
  if resultados_marcos_lista[i] == 'No':
    marcos_ausentes.append(marcos_lista[i])

print(marcos_ausentes)

marcos_crianca_selecionada = crianca['marcos']
#print(list(marcos_crianca_selecionada[1].keys())[0])
idade_crianca = int(crianca['idade_meses'])

lista_de_avaliacoes_presentes_ausentes = []
for i in range(len(marcos_crianca_selecionada)):
  for j in range(len(marcos_ausentes)):
    if list(marcos_crianca_selecionada[i].keys())[0] == marcos_ausentes[j]:
      registro_idade_mes = marcos_crianca_selecionada[i][marcos_ausentes[j]]['registro_idade_mes']
      #print(registro_idade_mes)
      limite_superior_faixa_etaria = marcos_crianca_selecionada[i][marcos_ausentes[j]]['limite_superior_faixa_etaria']
      #print(limite_superior_faixa_etaria)
      limite_inferior_faixa_etaria = marcos_crianca_selecionada[i][marcos_ausentes[j]]['limite_inferior_faixa_etaria']
      #print(limite_inferior_faixa_etaria)
      #print('----')

      if (idade_crianca <= 1):
        lista_de_avaliacoes_presentes_ausentes.append('atraso')

      else:
        if (idade_crianca >= int(limite_inferior_faixa_etaria) and idade_crianca <= int(limite_superior_faixa_etaria)):
          lista_de_avaliacoes_presentes_ausentes.append('alerta')

        else:
          lista_de_avaliacoes_presentes_ausentes.append('atraso')


print(lista_de_avaliacoes_presentes_ausentes)

"""### Resultado da avaliação da criança"""

is_dev_adequado = dev_adequado_crianca(crianca['nome'], marcos_lista)

if (is_dev_adequado):
  print("Desenvolvimento da criança está ADEQUADO.")
else:
  if "atraso" in lista_de_avaliacoes_presentes_ausentes:
    print('Desenvolvimento da criança está em ATRASO.')
  else:
    print('Desenvolvimento da criança está em ALERTA.')